services:
  devstash-db:
    image: postgres
    container_name: devstash-db
    user: 1000:1000
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: devstash
    ports:
      - 5433:5432
    volumes:
      - ../data:/var/lib/postgresql
